### ISSUE TITLE
Question about the math behind "Shannon's law samples/degree"

### ISSUE THREAD

**Issue by LightningDragon** [Pyrolistical/overwatch-dpi-tool#1]
So I was looking at the math trying to understand it and I saw that `dotpdeg` as a single expression is `((dpi * ((360.0 * 10.0 / 3.0) / (dpi * sensitvity * 0.022)) / 360.0) / 2.0)` looking at it as a single expression shows me that a lot of it cancels out notably dpi cancels it's self out. resulting in `((10.0 / 3.0) / (sensitvity * 0.022)) / 2.0`. meaning "Shannon's law samples/degree" is completely unaffected by a change in DPI, the DPI can be 1 or 999999 and and still give the same result, is this really correct? I thought the DPI was supposed to have an effect on pixel skipping etc.

**Comment by Pyrolistical** [comment]
you are correct that dpi cancels out, but if you notice in-game sensitivity is still there.  the reason why dpi matters is you want to maintain your overall sensitivity.  if you only decrease in-game sensitivity and don't change dpi, then your overall sensitivity would change.

so in order to maintain the same overall sensitivity and reduce pixel skipping, you first decrease in-game sensitivity (for pixel skipping), then increase dpi (for maintenance of overall sensitivity)

**Comment by wcn3** [comment]
Where does the 10/3 constant come from? With an eDPI of 5000 and yaw of 0.22, I'd expect a circle to take 3.3" but your tool scales by that constant and yields 10.9"

**Comment by LightningDragon** [comment]
@wcn3 it's 0.022 not 0.22 also. it's just a short hand for the conversion ratio for pixels to inches other wise it would be 0.00659824046920821114369501466276 quite the hand full. you could do the same thing with 54560 / edpi and that would give you the same in360.

**Comment by fuzzyweapon** [comment]
@Pyrolistical While the tool is useful for finding out what in game sensitivity is required for which resolution and FOV one wishes to play at, what's the point of including DPI if the tool isn't going to suggest a new DPI to maintain sensitivity feel?  Or at least give users a sweet spot where they won't experience side-effects?  Idle curiosity here, but as a near layman, I'm still left wondering what DPI I should have my mouse at.

Even displaying some suggested DPIs for the player to try out would be helpful.  They don't have to be perfect, just archetypal.  Visually perhaps just arranged within the typical range/sweet spot.  For instance:
Try n & n+200 shifter for quick turns with run and gun heroes (e.g. Sombra, Soldier 76).

Something like this could give newbs a starting point to figure out what works best for them.

**Comment by Pyrolistical** [comment]
??? the idea of the tool is to keep exactly the same overall sensitivity. If you feel a change in overall sensitivity, then you are either using the tool wrong or your mouse sensor doesn't support that dpi well.

**Comment by fuzzyweapon** [comment]
Maybe I'm misunderstanding something fundamentally.  If I change the DPI at all, it affects nothing in the tool (bc it is canceled out of the equation).  That means that in order to get my target resolution blue, I have to change the in-game sensitivity.  I do that, my overall sensitivity changes, and then I have to figure out how much DPI I need to adjust to approximate my former overall sensitivity?

That was my experience with it.

**Comment by Pyrolistical** [comment]
Correct. You lower in-game sensitivity and increase DPI, while maintaining overall sensitivity, until the targets are blue
